import type { RouteTagMapping } from "./tt-types.ts";

export const routeTagMapping: RouteTagMapping = {
  "/": {
    tags: [
      "s_cover_group",
      "s_cover_rep",
      "s_cover",
      "s_cover_item",
      "s_cover_item_article_info",
      "s_sidebar",
      "s_sidebar_element",
      "s_search",
      "s_rctps_rep",
      "s_random_tags",
      "s_notice",
    ],
    title: "메인 페이지",
    description: "블로그 메인 페이지입니다.",
  },
  "/posts": {
    tags: [
      "s_sidebar",
      "s_sidebar_element",
      "s_search",
      "s_rctps_rep",
      "s_random_tags",
      "s_notice",
      "s_article_rep",
      "s_permalink_article_rep",
      "s_article_rep_thumbnail",
      "s_article_prev",
      "s_article_prev_thumbnail",
      "s_article_next",
      "s_article_next_thumbnail",
      "s_article_related",
      "s_article_related_rep",
      "s_rp",
      "s_ad",
    ],
    title: "포스트 페이지",
    description: "블로그 포스트를 보여줍니다.",
  },
  "/category": {
    tags: [
      "s_list",
      "s_list_rep",
      "s_sidebar",
      "s_sidebar_element",
      "s_search",
      "s_rctps_rep",
      "s_random_tags",
      "s_notice",
    ],
    title: "카테고리 페이지",
    description: "카테고리별 글 목록입니다.",
  },
  "/tag": {
    tags: ["s_tag", "s_sidebar"],
    title: "태그 페이지",
    description: "태그 클라우드를 보여줍니다.",
  },
  "/archive": {
    tags: ["s_archive", "s_sidebar"],
    title: "보관함",
    description: "날짜별 글 보관함입니다.",
  },
  "/guestbook": {
    tags: ["s_guest", "s_sidebar"],
    title: "방명록",
    description: "방명록 페이지입니다.",
  },
  "/admin": {
    tags: ["s_admin"],
    title: "관리자",
    description: "관리자 페이지입니다.",
  },
};
